### ISSUE TITLE
Bug in deploy/operator.yaml,  non existing image name: `mumoshu/falco-operator:v0.12.1`, CRD's not automatically deployed

### ISSUE THREAD

**Issue by Michael-Frank** [falcosecurity-retire/falco-operator#9]
Hi @mumoshu,
thanks for contributing an operator for falco!

During our first test we discovered some issues i would like to share.
To get falco-operator running we had to:
- remove the ‘v’ from image version `v0.12.1` => to look like: `0.12.1` in these files (related: #2):
    - `charts/falco-operator/values.yaml`
    - `deploy/operator.yaml`
- Fix `deploy/operator.yaml` to use operator generated resource name for configMap:
  - change:
  ```yaml
        - name: falco-operator-rules
          configMap:
            name: falco-operator  
  ```
  - to: 
  ```yaml
         - name: falco-operator-rules
            configMap:
              name: {{ template "falco.fullname" . }}

- manually install the CRD files - as operator does not deploy these two (requires cluster Admin rights)
  The readme.md unfortunatly does not highlight this issue.
  ```bash
  k apply --namespace falco -f deploy/crd.yaml
  k apply --namespace falco -f deploy/cr.yaml
  ```
### walk through 
Our complete walk through (which may be helpful for others to get started) including requirements, encountered errors and fixes for them:
[falco-operator-install-walkthrough.md](https://github.com/falcosecurity/falco-operator/files/3217452/falco-operator-install-walkthrough-publish.md.txt)
